// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WorkplannerWebApi
{
    public partial class Access
    {
        public Access()
        {
            Users = new HashSet<User>();
        }

        public int AccessLevel { get; set; }
        public string AccessDescription { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}