// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WorkplannerWebApi
{
    public partial class EmployeeInformation
    {
        public EmployeeInformation()
        {
            Employees = new HashSet<Employee>();
        }

        public int EinformationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public string City { get; set; }
        public int ZipPostal { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
    }
}