// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WorkplannerWebApi
{
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public int UserId { get; set; }
        public int EinformationId { get; set; }

        public virtual EmployeeInformation Einformation { get; set; }
        public virtual User User { get; set; }
    }
}