INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bob', 'Seequel', 23232323, 'bob@bobs.dk',1)
INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bobbi', 'Seequel', 24242424, 'bobbi@bobs.dk',2)
INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bobsa', 'Seequel', 25252525, 'bobsa@bobs.dk',3)
INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bobsai', 'Seequel', 26262626, 'bobsai@bobs.dk',4)
INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bobla', 'Seequel', 27272727, 'bobla@bobs.dk',5)
INSERT INTO Employee(FirstName,LastName,PhoneNumber,Email,UserID) VALUES ('Bobil', 'Seequel', 28282828, 'bobil@bobs.dk',6)

INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode1',1)
INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode2',1)
INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode3',1)
INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode4',2)
INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode5',3)
INSERT INTO Users(UserPassword,AccessLevel) VALUES ('kode6',1)

INSERT INTO Access(AccessLevel,AccessDescription) VALUES (0, 'Guest')
INSERT INTO Access(AccessLevel,AccessDescription) VALUES (1, 'User')
INSERT INTO Access(AccessLevel,AccessDescription) VALUES (2, 'Admin')
INSERT INTO Access(AccessLevel,AccessDescription) VALUES (3, 'SuperAdmin')